name: Update Fork

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          repository: reactjs/hi.react.dev
        
      - name: Checkout forked repository
        uses: actions/checkout@v2
      
      - name: Update fork
        run: |
          cd hi.react.dev
          git remote add upstream https://github.com/reactjs/hi.react.dev
          git fetch upstream
          git merge upstream/main
          git push origin main
